//Nome: Marjory Mel Ferreira Ferro Lemos - RA: 2564238

package com.mycompany.projperfumaria;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author marjory
 */
public class CadSplash extends javax.swing.JFrame {
    private Splash s1 = new Splash();
    private BdSplash gs = BdSplash.geraGerSplash();
    private static CadSplash csUnic;

    /**
     * Creates new form CadSplash
     */
    public CadSplash() {
        initComponents();
    }

    // Método Singleton
    public static CadSplash geraCadSplash(){
        if(csUnic == null){
            csUnic = new CadSplash();
        }
        return csUnic;
   }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cxNomeSplash = new javax.swing.JTextField();
        cxPrecoSplash = new javax.swing.JTextField();
        cxCodProdutoSplash = new javax.swing.JTextField();
        cxCupomSplash = new javax.swing.JTextField();
        cxAnoAtualSplash = new javax.swing.JTextField();
        rtNomeSplash = new javax.swing.JLabel();
        cxAplicacao = new javax.swing.JTextField();
        rtPrecoSplash = new javax.swing.JLabel();
        cxPercentualFragrancia = new javax.swing.JTextField();
        rtCodProdutoSplash = new javax.swing.JLabel();
        rtValidadeSplash = new javax.swing.JLabel();
        rtCupomSplash = new javax.swing.JLabel();
        rtAnoAtualSplash = new javax.swing.JLabel();
        cxValidadeSplash = new javax.swing.JTextField();
        rtAplicacao = new javax.swing.JLabel();
        rtPercentualFragrancia = new javax.swing.JLabel();
        btCosSplash = new javax.swing.JButton();
        btAltSplash = new javax.swing.JButton();
        btExcluirSplash = new javax.swing.JButton();
        btInsSplash = new javax.swing.JButton();
        btLimparSplash = new javax.swing.JButton();
        btSairSplash = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSplash = new javax.swing.JTable();
        btInfoSplash = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cxNomeSplash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxNomeSplashActionPerformed(evt);
            }
        });

        cxPrecoSplash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxPrecoSplashActionPerformed(evt);
            }
        });

        cxCupomSplash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxCupomSplashActionPerformed(evt);
            }
        });

        cxAnoAtualSplash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxAnoAtualSplashActionPerformed(evt);
            }
        });

        rtNomeSplash.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rtNomeSplash.setText("Nome do Produto:");

        cxAplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxAplicacaoActionPerformed(evt);
            }
        });

        rtPrecoSplash.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rtPrecoSplash.setText("Preço do Produto:");

        rtCodProdutoSplash.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rtCodProdutoSplash.setText("ID do Produto:");

        rtValidadeSplash.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rtValidadeSplash.setText("Ano de Validade:");

        rtCupomSplash.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rtCupomSplash.setText("Cupom (%):");

        rtAnoAtualSplash.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rtAnoAtualSplash.setText("Ano Atual:");

        rtAplicacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rtAplicacao.setText("Aplicação (Ml):");

        rtPercentualFragrancia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rtPercentualFragrancia.setText("Fragrância (%):");

        btCosSplash.setText("Consultar");
        btCosSplash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCosSplashActionPerformed(evt);
            }
        });

        btAltSplash.setText("Alterar Preço");
        btAltSplash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAltSplashActionPerformed(evt);
            }
        });

        btExcluirSplash.setText("Excluir");
        btExcluirSplash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirSplashActionPerformed(evt);
            }
        });

        btInsSplash.setText("Inserir");
        btInsSplash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsSplashActionPerformed(evt);
            }
        });

        btLimparSplash.setText("Limpar");
        btLimparSplash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparSplashActionPerformed(evt);
            }
        });

        btSairSplash.setText("Sair");
        btSairSplash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairSplashActionPerformed(evt);
            }
        });

        tbSplash.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nome", "Preço"
            }
        ));
        tbSplash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSplashMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbSplash);

        btInfoSplash.setText("Informação");
        btInfoSplash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInfoSplashActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rtCodProdutoSplash, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rtPrecoSplash, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rtNomeSplash, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addComponent(rtValidadeSplash, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(rtAplicacao)
                    .addComponent(rtPercentualFragrancia)
                    .addComponent(rtCupomSplash)
                    .addComponent(rtAnoAtualSplash))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cxPercentualFragrancia, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btInfoSplash)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btLimparSplash)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btSairSplash))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cxCodProdutoSplash, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addComponent(btInsSplash)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btCosSplash)
                                .addGap(12, 12, 12)
                                .addComponent(btAltSplash)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btExcluirSplash))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cxCupomSplash)
                                        .addComponent(cxValidadeSplash)
                                        .addComponent(cxAnoAtualSplash, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cxAplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cxNomeSplash, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(cxPrecoSplash, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxCodProdutoSplash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rtCodProdutoSplash)
                    .addComponent(btInsSplash)
                    .addComponent(btCosSplash)
                    .addComponent(btAltSplash)
                    .addComponent(btExcluirSplash))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cxNomeSplash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rtNomeSplash))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cxPrecoSplash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rtPrecoSplash))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cxCupomSplash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rtCupomSplash))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cxValidadeSplash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rtValidadeSplash))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cxAnoAtualSplash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rtAnoAtualSplash))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cxAplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rtAplicacao)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxPercentualFragrancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rtPercentualFragrancia)
                    .addComponent(btLimparSplash)
                    .addComponent(btSairSplash)
                    .addComponent(btInfoSplash))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cxNomeSplashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxNomeSplashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxNomeSplashActionPerformed

    private void cxPrecoSplashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxPrecoSplashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxPrecoSplashActionPerformed

    private void cxCupomSplashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxCupomSplashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxCupomSplashActionPerformed

    private void cxAnoAtualSplashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxAnoAtualSplashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxAnoAtualSplashActionPerformed

    private void cxAplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxAplicacaoActionPerformed

    }//GEN-LAST:event_cxAplicacaoActionPerformed

    private void btCosSplashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCosSplashActionPerformed
        consSplashID();
    }//GEN-LAST:event_btCosSplashActionPerformed

    private void btAltSplashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAltSplashActionPerformed
        altSplashID();
        listTabSplash();
    }//GEN-LAST:event_btAltSplashActionPerformed

    private void btExcluirSplashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirSplashActionPerformed
        excSplashID();
        listTabSplash();
    }//GEN-LAST:event_btExcluirSplashActionPerformed

    private void btInsSplashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInsSplashActionPerformed
        insSplash();
        listTabSplash();
        limparSplash();
    }//GEN-LAST:event_btInsSplashActionPerformed

    private void btLimparSplashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparSplashActionPerformed
        limparSplash();
    }//GEN-LAST:event_btLimparSplashActionPerformed

    private void btSairSplashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairSplashActionPerformed
        sairSplash();
    }//GEN-LAST:event_btSairSplashActionPerformed

    private void tbSplashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSplashMouseClicked
        selectTabSplash();
    }//GEN-LAST:event_tbSplashMouseClicked

    private void btInfoSplashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInfoSplashActionPerformed
        info();
    }//GEN-LAST:event_btInfoSplashActionPerformed
    
    public void listTabSplash(){
        DefaultTableModel modelo = (DefaultTableModel)tbSplash.getModel();
        int posLin = 0;
        
        modelo.setRowCount(posLin);
        
        for(Splash spl:gs.getBdSplash()){ 
            modelo.insertRow(posLin, new Object[]{spl.getCodProduto(),spl.getNome(), spl.getPreco()});
            posLin++;
        }
    }
    
    public void selectTabSplash(){
        String valLinTab = "";
        
        int posLin = tbSplash.getSelectedRow();
        int col = 0;
        for(col = 0; col < tbSplash.getColumnCount(); col++){
            valLinTab += tbSplash.getModel().getValueAt(posLin, col).toString();
            
            if(col+1 < tbSplash.getColumnCount()){
                valLinTab += " - ";
            }
        }
        
        float desconto = s1.calc(s1.getCupom(), s1.getPreco());
        float validadePreco = s1.calc(s1.getPreco(),s1.getValidade(),s1.getAnoAtual());
        float validadeRestante = s1.calcular();
        
                JOptionPane.showMessageDialog(
                null,
                "\nID do produto: " + s1.getCodProduto()+
                "\nNome do produto: " + s1.getNome()+
                "\nPreço do produto: " + s1.getPreco()+
                "\nCupom em percentual: " + s1.getCupom()+
                "\nAno de validade: " + s1.getValidade()+
                "\nAno atual: " + s1.getAnoAtual()+
                "\nAplicação (ml): " +s1.getAplicacaoMl()+
                "\nFragrância (%): " +s1.getPercentualFragrancia()+
                "\nDesconto com cupom: " + desconto + 
                "\nRelação preço/validade : " + validadePreco + 
                "\nValidade restante: " + validadeRestante + " anos",
                "RESULTADOS DO PRODUTO: ",
                1
        );
    }
    
    public void excSplashID(){
        s1 = new Splash();
        
        s1.setCodProduto(Integer.parseInt(cxCodProdutoSplash.getText()));
        
        s1 = gs.delSplashID(s1);
        
        if(s1 == null){
    
            JOptionPane.showMessageDialog(
                    null,
                    "Produto excluido com sucesso!",
                    "EXCLUSÃO DE PRODUTO",
                    1
            );
            limparSplash();
        }
        else{
                    JOptionPane.showMessageDialog(
                    null,
                    "NÃO EXISTE PRODUTO COM ESTE ID",
                    "EXCLUSÃO DE PRODUTO",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }
    
public void altSplashID() {
    try {
        s1 = new Splash();

        s1.setCodProduto(Integer.parseInt(cxCodProdutoSplash.getText()));

        s1 = gs.atualizaSplashID(s1);

        if (s1 != null) {
            cxCodProdutoSplash.setText(Integer.toString(s1.getCodProduto()));
            cxNomeSplash.setText(s1.getNome());
            cxPrecoSplash.setText(Float.toString(s1.getPreco()));
            cxCupomSplash.setText(Float.toString(s1.getCupom()));
            cxValidadeSplash.setText(Float.toString(s1.getValidade()));
            cxAnoAtualSplash.setText(Float.toString(s1.getAnoAtual()));
            cxAplicacao.setText(Integer.toString(s1.getAplicacaoMl()));
            cxPercentualFragrancia.setText(Integer.toString(s1.getPercentualFragrancia()));

            JOptionPane.showMessageDialog(
                    null,
                    "Confira os dados!",
                    "ALTERAÇÃO DE PRODUTO",
                    JOptionPane.INFORMATION_MESSAGE
            );
            limparSplash();
        } else {
            JOptionPane.showMessageDialog(
                    null,
                    "NÃO EXISTE PRODUTO COM ESTE CÓDIGO",
                    "ALTERAÇÃO DE PRODUTO",
                    JOptionPane.ERROR_MESSAGE
            );
        }
            } catch (NumberFormatException nfe) {
                    JOptionPane.showMessageDialog(
                        null,
                        "Verifique os valores inseridos!",
                        "ERRO ENTRADA DE DADOS",
                        JOptionPane.ERROR_MESSAGE
            );
            cxCodProdutoSplash.setText("");
            cxCodProdutoSplash.requestFocus();
    }
}

    
    public void consSplashID(){
        s1 = new Splash();
    
        s1.setCodProduto(Integer.parseInt(cxCodProdutoSplash.getText()));
        
        s1 = gs.consSplashID(s1);
        
        if(s1 != null){
            cxCodProdutoSplash.setText(Integer.toString(s1.getCodProduto()));
            cxNomeSplash.setText(s1.getNome());
            cxPrecoSplash.setText(Float.toString(s1.getPreco()));
            cxCupomSplash.setText(Float.toString(s1.getCupom()));
            cxValidadeSplash.setText(Float.toString(s1.getValidade()));
            cxAnoAtualSplash.setText(Float.toString(s1.getAnoAtual()));
            cxAplicacao.setText(Integer.toString(s1.getAplicacaoMl()));
            cxPercentualFragrancia.setText(Integer.toString(s1.getPercentualFragrancia()));
            
            JOptionPane.showMessageDialog(
                    null,
                    "Produto encontrado com sucesso! - Verifique os dados",
                    "CONSULTA DE PRODUTO",
                    1
            );
        }
        else{
                    JOptionPane.showMessageDialog(
                    null,
                    "Esse produto não existe!",
                    "CONSULTA DE PRODUTO",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }
    
    public void insSplash(){
        try{
            s1 = new Splash();

            s1.setCodProduto(Integer.parseInt(cxCodProdutoSplash.getText()));
            s1.setNome(cxNomeSplash.getText());
            s1.setPreco(Float.parseFloat(cxPrecoSplash.getText()));

            try{
                s1.setCupom(Float.parseFloat(cxCupomSplash.getText()));
            }
                catch(CupomException cupom){
                    cupom.impCupom();
                    s1 = cupom.corCupomSplash(s1);
            }
            s1.setValidade(Float.parseFloat(cxValidadeSplash.getText()));

            try{
                s1.setAnoAtual(Float.parseFloat(cxAnoAtualSplash.getText()));
            }
            catch(AnoAtualException year){
                    year.impAnoAtual();
                    s1 = year.corAnoSplash(s1);
            }

            s1.setAplicacaoMl(Integer.parseInt(cxAplicacao.getText()));
            s1.setPercentualFragrancia(Integer.parseInt(cxPercentualFragrancia.getText()));

            s1 = gs.insSplash(s1);

                if(s1 != null){
                    JOptionPane.showMessageDialog(
                            null,
                            "Produto cadastrado com sucesso!",
                            "CADASTRO DE PRODUTO",
                            1
                    );
                }
                else{
                    JOptionPane.showMessageDialog(
                            null,
                            "Produto duplicado",
                            "CADASTRO DE PRODUTO",
                            JOptionPane.ERROR_MESSAGE
                    );
                }
            }
            catch(NumberFormatException nfe){
                        JOptionPane.showMessageDialog(
                        null,
                        "Verifique os valores inseridos!",
                        "ERRO ENTRADA DE DADOS",
                        JOptionPane.ERROR_MESSAGE
                ); 
                cxCodProdutoSplash.setText("");
                cxCodProdutoSplash.requestFocus();
            }
    }
    
    public void sairSplash(){
        int resp = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente sair?",
                "SAIR",
                JOptionPane.YES_NO_OPTION
        );
        if(resp == 0){
            dispose();
        }
    }
    
    public void limparSplash(){
        cxCodProdutoSplash.setText("");
        cxNomeSplash.setText("");
        cxPrecoSplash.setText("");
        cxCupomSplash.setText("");
        cxValidadeSplash.setText("");
        cxAnoAtualSplash.setText("");
        cxAplicacao.setText("");
        cxPercentualFragrancia.setText("");
        cxCodProdutoSplash.requestFocus();
    }
    
    public void info(){
        Splash bt = new Splash();
        bt.explicacaoProduto();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadSplash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAltSplash;
    private javax.swing.JButton btCosSplash;
    private javax.swing.JButton btExcluirSplash;
    private javax.swing.JButton btInfoSplash;
    private javax.swing.JButton btInsSplash;
    private javax.swing.JButton btLimparSplash;
    private javax.swing.JButton btSairSplash;
    private javax.swing.JTextField cxAnoAtualSplash;
    private javax.swing.JTextField cxAplicacao;
    private javax.swing.JTextField cxCodProdutoSplash;
    private javax.swing.JTextField cxCupomSplash;
    private javax.swing.JTextField cxNomeSplash;
    private javax.swing.JTextField cxPercentualFragrancia;
    private javax.swing.JTextField cxPrecoSplash;
    private javax.swing.JTextField cxValidadeSplash;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel rtAnoAtualSplash;
    private javax.swing.JLabel rtAplicacao;
    private javax.swing.JLabel rtCodProdutoSplash;
    private javax.swing.JLabel rtCupomSplash;
    private javax.swing.JLabel rtNomeSplash;
    private javax.swing.JLabel rtPercentualFragrancia;
    private javax.swing.JLabel rtPrecoSplash;
    private javax.swing.JLabel rtValidadeSplash;
    private javax.swing.JTable tbSplash;
    // End of variables declaration//GEN-END:variables
}
