//Nome: Marjory Mel Ferreira Ferro Lemos - RA: 2564238

package com.mycompany.projperfumaria;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marjory
 */
public class RelatGeralHidra extends javax.swing.JFrame {

    private static RelatGeralHidra rghUnic;
    
    /**
     * Creates new form RelatGeralHidra
     */
    public RelatGeralHidra() {
        initComponents();
    }
    
    // Método Singleton
    public static RelatGeralHidra geraRelGerHidra(){
            if (rghUnic == null){
                rghUnic = new RelatGeralHidra();
            }
            return rghUnic;
    }
    
    public void listTab(){
        DefaultTableModel modelo = (DefaultTableModel)tbRelHidra.getModel();
        int posLin = 0;
        
        modelo.setRowCount(posLin);
        
        for(Hidratante hidra:BdHidratante.geraGerHidra().getBdHidra()){
            modelo.insertRow(posLin, new Object[]{hidra.getCodProduto(),hidra.getNome(), hidra.getPreco(),hidra.getCupom(), hidra.getValidade(), hidra.getAnoAtual(), hidra.getFatorHidratacao(), hidra.getProtecaoSolar()});
            posLin++;
        }
        
    }
    
    public void selectTab(){
    
        String valLinTab = "";
        
        int posLin = tbRelHidra.getSelectedRow();
        int col = 0;
        for(col = 0; col < tbRelHidra.getColumnCount(); col++){
            valLinTab += tbRelHidra.getModel().getValueAt(posLin, col).toString();
            
            if(col+1 < tbRelHidra.getColumnCount()){
                valLinTab += " - ";
            }
        }
        
        JOptionPane.showMessageDialog(
                null,
                "Conteudo: "+valLinTab,
                "Valores do Produto: ",
                1
        );
    }
    
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente sair?",
                "SAIR",
                JOptionPane.YES_NO_OPTION
        );
        if(resp == 0){
            dispose();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbRelHidra = new javax.swing.JTable();
        btSairRelHidra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        tbRelHidra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Preço", "Cupom", "Ano de Validade", "Ano Atual", "Hidratação", "Proteção Solar"
            }
        ));
        tbRelHidra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbRelHidraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbRelHidra);

        btSairRelHidra.setText("Sair");
        btSairRelHidra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairRelHidraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSairRelHidra)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSairRelHidra)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listTab();
    }//GEN-LAST:event_formWindowActivated

    private void btSairRelHidraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairRelHidraActionPerformed
        sair();
    }//GEN-LAST:event_btSairRelHidraActionPerformed

    private void tbRelHidraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbRelHidraMouseClicked
        selectTab();
    }//GEN-LAST:event_tbRelHidraMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatGeralHidra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatGeralHidra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatGeralHidra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatGeralHidra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatGeralHidra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSairRelHidra;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbRelHidra;
    // End of variables declaration//GEN-END:variables
}
