//Nome: Marjory Mel Ferreira Ferro Lemos - RA: 2564238

package com.mycompany.projperfumaria;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marjory
 */
public class RelatGeralSplash extends javax.swing.JFrame {
    
    private static RelatGeralSplash rgsUnic;

    /**
     * Creates new form RelatGeralSplash
     */
    public RelatGeralSplash() {
        initComponents();
    }
    
    // Método Singleton
    public static RelatGeralSplash geraRelGerSplash(){
            if (rgsUnic == null){
                rgsUnic = new RelatGeralSplash();
            }
            return rgsUnic;
    }
    
    public void listTab(){
        DefaultTableModel modelo = (DefaultTableModel)tbRelSplash.getModel();
        int posLin = 0;
        
        modelo.setRowCount(posLin);
        
        for(Splash spl:BdSplash.geraGerSplash().getBdSplash()){
            modelo.insertRow(posLin, new Object[]{spl.getCodProduto(),spl.getNome(), spl.getPreco(),spl.getCupom(), spl.getValidade(), spl.getAnoAtual(), spl.getAplicacaoMl(), spl.getPercentualFragrancia()});
            posLin++;
        }
    }

    public void selectTab(){
    
        String valLinTab = "";
        
        int posLin = tbRelSplash.getSelectedRow();
        int col = 0;
        for(col = 0; col < tbRelSplash.getColumnCount(); col++){
            valLinTab += tbRelSplash.getModel().getValueAt(posLin, col).toString();
            
            if(col+1 < tbRelSplash.getColumnCount()){
                valLinTab += " - ";
            }
        }
        
        JOptionPane.showMessageDialog(
                null,
                "Conteudo: "+valLinTab,
                "Valores do Produto: ",
                1
        );
    }
    
    public void sair(){
        int resp = JOptionPane.showConfirmDialog(
                null,
                "Deseja realmente sair?",
                "SAIR",
                JOptionPane.YES_NO_OPTION
        );
        if(resp == 0){
            dispose();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbRelSplash = new javax.swing.JTable();
        btSairRelSplash = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        tbRelSplash.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Preço", "Cupom", "Ano de Validade", "Ano Atual", "Aplicação (Ml)", "Fragrância (%)"
            }
        ));
        tbRelSplash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbRelSplashMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbRelSplash);

        btSairRelSplash.setText("Sair");
        btSairRelSplash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairRelSplashActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSairRelSplash)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSairRelSplash)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbRelSplashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbRelSplashMouseClicked
        selectTab();
    }//GEN-LAST:event_tbRelSplashMouseClicked

    private void btSairRelSplashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairRelSplashActionPerformed
        sair();
    }//GEN-LAST:event_btSairRelSplashActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listTab();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatGeralSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatGeralSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatGeralSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatGeralSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatGeralSplash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSairRelSplash;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbRelSplash;
    // End of variables declaration//GEN-END:variables
}
